version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - db_data:/var/lib/mysql
#    networks:
#      - backend

  phpmyadmin:
    platform: linux/x86_64
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
#    networks:
#      - backend

  express_client:
    image: node:latest
    container_name: express_client
    build: .
#    depends_on:
#      - mysql
    restart: always
    environment:
      - PORT=4000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
#    networks:
#      - backend

  express_admin:
    image: node:latest
    container_name: express_admin
    build: .
#    depends_on:
#      - mysql
    restart: always
    environment:
      - ROUTER_ADMIN=ROUTER_ADMIN
      - PORT=4000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
#    networks:
#      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_server
    depends_on:
      - express_client
      - express_admin
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
#    networks:
#      - backend

#networks:
#  backend:
#    driver: bridge

volumes:
  db_data:
